baseURL: "https://mrturkmen.com/"
title: mrturkmen
theme: dream

params:
  env: production
  title: Ahmet Turkmen
  description: "Contains notes and blog posts"
  keywords: [gRPC, docker, go, golang, cloud, virtualization, python]
  author: mrturkmen
  images: ["static"]
  
  # Dream theme specific settings
  avatar: "content/images/profile.jpg"
  subtitle: "Systems Development Engineer at Amazon"
  
  social:
    - name: github
      url: "https://github.com/mrtrkmn"
    - name: linkedin
      url: "https://linkedin.com/in/mrturkmen"
    - name: gitlab
      url: "https://gitlab.com/mrturkmen"
    - name: email
      url: "mailto:hi@mrturkmen.com"

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 10
    - name: Archive
      url: /archives/
      weight: 20
    - name: Search
      url: /search/
      weight: 30

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-165248542-1

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
